In [1]:
#Import and load data

import os
import csv
import pandas as pd
import geopandas as gpd

cd = gpd.read_file("data/CD/lcd_000b21a_e.shp")
csd = gpd.read_file("data/CSD/lcsd000b21a_e.shp")
cma = gpd.read_file("data/CMA/lcma000b21a_e.shp")

In [2]:
#Spatial join because no common column to make a standard join

sjoin = gpd.sjoin(csd , cma , how = 'left')
sjoin.head()

,CSDUID,DGUID_left,CSDNAME,CSDTYPE,LANDAREA_left,PRUID_left,geometry,index_right,CMAUID,CMAPUID,DGUID_right,DGUIDP,CMANAME,CMATYPE,LANDAREA_right,PRUID_right
0,1001101,2021A00051001101,"Division No. 1, Subd. V",SNO,870.8928,10,"MULTIPOLYGON (((8991051.954 2038839.069, 89910...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1001105,2021A00051001105,Portugal Cove South,T,1.0770,10,"POLYGON ((9001504.369 2049856.597, 9001184.977...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1001113,2021A00051001113,Trepassey,T,54.2130,10,"POLYGON ((8992311.551 2054468.074, 8994001.626...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1001120,2021A00051001120,St. Shott's,T,1.0729,10,"POLYGON ((8985240.566 2028560.540, 8984967.974...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1001124,2021A00051001124,"Division No. 1, Subd. U",SNO,742.3781,10,"MULTIPOLYGON (((8995265.971 2098624.091, 89952...",0.0,001,10001,2021S0503001,None,St. John's,B,931.5637,10

In [3]:
#Shortening the CSDUID so that it can be joined with the CD table

sjoin['CSDUID_short'] = sjoin['CSDUID'].str[:4]
sjoin.head()

,CSDUID,DGUID_left,CSDNAME,CSDTYPE,LANDAREA_left,PRUID_left,geometry,index_right,CMAUID,CMAPUID,DGUID_right,DGUIDP,CMANAME,CMATYPE,LANDAREA_right,PRUID_right,CSDUID_short
0,1001101,2021A00051001101,"Division No. 1, Subd. V",SNO,870.8928,10,"MULTIPOLYGON (((8991051.954 2038839.069, 89910...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1001
1,1001105,2021A00051001105,Portugal Cove South,T,1.0770,10,"POLYGON ((9001504.369 2049856.597, 9001184.977...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1001
2,1001113,2021A00051001113,Trepassey,T,54.2130,10,"POLYGON ((8992311.551 2054468.074, 8994001.626...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1001
3,1001120,2021A00051001120,St. Shott's,T,1.0729,10,"POLYGON ((8985240.566 2028560.540, 8984967.974...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1001
4,1001124,2021A00051001124,"Division No. 1, Subd. U",SNO,742.3781,10,"MULTIPOLYGON (((8995265.971 2098624.091, 89952...",0.0,001,10001,2021S0503001,None,St. John's,B,931.5637,10,1001

In [4]:
#Joining the CD table

full_join = pd.merge(cd , sjoin , left_on = 'CDUID' , right_on = 'CSDUID_short')
full_join.head()

,CDUID,DGUID,CDNAME,CDTYPE,LANDAREA,PRUID,geometry_x,CSDUID,DGUID_left,CSDNAME,...,index_right,CMAUID,CMAPUID,DGUID_right,DGUIDP,CMANAME,CMATYPE,LANDAREA_right,PRUID_right,CSDUID_short
0,1001,2021A00031001,Division No. 1,CDR,9104.5799,10,"MULTIPOLYGON (((8991051.954 2038839.069, 89910...",1001101,2021A00051001101,"Division No. 1, Subd. V",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1001
1,1001,2021A00031001,Division No. 1,CDR,9104.5799,10,"MULTIPOLYGON (((8991051.954 2038839.069, 89910...",1001105,2021A00051001105,Portugal Cove South,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1001
2,1001,2021A00031001,Division No. 1,CDR,9104.5799,10,"MULTIPOLYGON (((8991051.954 2038839.069, 89910...",1001113,2021A00051001113,Trepassey,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1001
3,1001,2021A00031001,Division No. 1,CDR,9104.5799,10,"MULTIPOLYGON (((8991051.954 2038839.069, 89910...",1001120,2021A00051001120,St. Shott's,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1001
4,1001,2021A00031001,Division No. 1,CDR,9104.5799,10,"MULTIPOLYGON (((8991051.954 2038839.069, 89910...",1001124,2021A00051001124,"Division No. 1, Subd. U",...,0.0,001,10001,2021S0503001,None,St. John's,B,931.5637,10,1001

In [9]:
#Filter census data within the GGH

ggh = full_join.loc[(full_join['CSDUID'].str.contains("3543"))|# Simcoe
                        (full_join['CSDUID'].str.contains("3522"))|# Dufferin
                        (full_join['CSDUID'].str.contains("3523"))|# Wellington
                        (full_join['CSDUID'].str.contains("3516"))|# Kawartha Lakes
                        (full_join['CSDUID'].str.contains("3515"))|# Peterborough
                        (full_join['CSDUID'].str.contains("3514"))|# Northumberland
                        (full_join['CSDUID'].str.contains("3518"))|# Durham
                        (full_join['CSDUID'].str.contains("3519"))|# York
                        (full_join['CSDUID'].str.contains("3520"))|# Toronto
                        (full_join['CSDUID'].str.contains("3521"))|# Peel
                        (full_join['CSDUID'].str.contains("3524"))|# Halton
                        (full_join['CSDUID'].str.contains("3530"))|# Waterloo
                        (full_join['CSDUID'].str.contains("3525"))|# Hamilton
                        (full_join['CSDUID'].str.contains("3529"))|# Brant
                        (full_join['CSDUID'].str.contains("3526"))|# Niagara
                        (full_join['CSDUID'].str.contains("3528"))]# Haldimand-Norlfolk
ggh

,CDUID,DGUID,CDNAME,CDTYPE,LANDAREA,PRUID,geometry_x,CSDUID,DGUID_left,CSDNAME,...,index_right,CMAUID,CMAPUID,DGUID_right,DGUIDP,CMANAME,CMATYPE,LANDAREA_right,PRUID_right,CSDUID_short
2262,3514,2021A00033514,Northumberland,CTY,1907.3955,35,"MULTIPOLYGON (((7352171.091 999144.226, 735216...",3514004,2021A00053514004,Brighton,...,57.0,522,35522,2021S0503522,None,Belleville - Quinte West,B,1337.4982,35,3514
2263,3514,2021A00033514,Northumberland,CTY,1907.3955,35,"MULTIPOLYGON (((7352171.091 999144.226, 735216...",3514014,2021A00053514014,Cramahe,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3514
2264,3514,2021A00033514,Northumberland,CTY,1907.3955,35,"MULTIPOLYGON (((7352171.091 999144.226, 735216...",3514019,2021A00053514019,Hamilton,...,58.0,527,35527,2021S0504527,None,Cobourg,D,22.4072,35,3514
2265,3514,2021A00033514,Northumberland,CTY,1907.3955,35,"MULTIPOLYGON (((7352171.091 999144.226, 735216...",3514019,2021A00053514019,Hamilton,...,59.0,528,35528,2021S0504528,None,Port Hope,D,278.8012,35,3514
2266,3514,2021A00033514,Northumberland,CTY,1907.3955,35,"MULTIPOLYGON (((7352171.091 999144.226, 735216...",3514020,2021A00053514020,Port Hope,...,63.0,532,35532,2021S0503532,None,Oshawa,B,903.2512,35,3514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2564,3543,2021A00033543,Simcoe,CTY,4818.9317,35,"MULTIPOLYGON (((7177118.911 1047854.583, 71771...",3543070,2021A00053543070,Christian Island 30A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3543
2565,3543,2021A00033543,Simcoe,CTY,4818.9317,35,"MULTIPOLYGON (((7177118.911 1047854.583, 71771...",3543071,2021A00053543071,Tay,...,83.0,568,35568,2021S0503568,None,Barrie,B,897.2559,35,3543
2566,3543,2021A00033543,Simcoe,CTY,4818.9317,35,"MULTIPOLYGON (((7177118.911 1047854.583, 71771...",3543071,2021A00053543071,Tay,...,85.0,571,35571,2021S0504571,None,Midland,D,60.7517,35,3543
2567,3543,2021A00033543,Simcoe,CTY,4818.9317,35,"MULTIPOLYGON (((7177118.911 1047854.583, 71771...",3543072,2021A00053543072,Penetanguishene,...,85.0,571,35571,2021S0504571,None,Midland,D,60.7517,35,3543
2568,3543,2021A00033543,Simcoe,CTY,4818.9317,35,"MULTIPOLYGON (((7177118.911 1047854.583, 71771...",3543074,2021A00053543074,Midland,...,85.0,571,35571,2021S0504571,None,Midland,D,60.7517,35,3543

In [11]:
# Subset the data for what is actually needed

ggh_sub = ggh[["CDNAME" , "CDUID" , "CSDNAME" , "CSDUID" , "CMANAME", "CMAUID" , "CMAPUID"]]
ggh_sub

,CDNAME,CDUID,CSDNAME,CSDUID,CMANAME,CMAUID,CMAPUID
2262,Northumberland,3514,Brighton,3514004,Belleville - Quinte West,522,35522
2263,Northumberland,3514,Cramahe,3514014,NaN,NaN,NaN
2264,Northumberland,3514,Hamilton,3514019,Cobourg,527,35527
2265,Northumberland,3514,Hamilton,3514019,Port Hope,528,35528
2266,Northumberland,3514,Port Hope,3514020,Oshawa,532,35532
...,...,...,...,...,...,...,...
2564,Simcoe,3543,Christian Island 30A,3543070,NaN,NaN,NaN
2565,Simcoe,3543,Tay,3543071,Barrie,568,35568
2566,Simcoe,3543,Tay,3543071,Midland,571,35571
2567,Simcoe,3543,Penetanguishene,3543072,Midland,571,35571
2568,Simcoe,3543,Midland,3543074,Midland,571,35571

In [12]:
#export

ggh_sub.to_csv('ggh_boundaries.csv', index = False)